name: test deployment

on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    environment:
      name: staging
      url: https://github.com
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!
